server.port: 8848
spring:
  datasource:
    dynamic:
      primary: mysql
      datasource:
        mysql:
          url: jdbc:mysql://localhost:3306/statistic?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
          username: root
          password: xxx
          driver-class-name: com.mysql.cj.jdbc.Driver
        sqlite:
          url: jdbc:sqlite:chromeHistory.db
          driver-class-name: org.sqlite.JDBC

  task:
    execution:
      pool:
        core-size: 5
        max-size: 15
        queue-capacity: 100
    scheduling:
      pool:
        size: 5

  rabbitmq:
    addresses: localhost
    port: 5672
    virtual-host: /
    stream:
      username: guest
      password: guest
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual



mybatis-plus:
  mapper-locations: com.wenli.mapper/*.xml
  type-aliases-package: com.wenli.entity.po