server.port: 8899
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/statistic?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: xxxx
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: com.wenli.mapper/*.xml
  type-aliases-package: com.wenli.entity.po